# Generated by Django 3.1 on 2023-09-04 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cartitem_cariations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='cariations',
            new_name='variations',
        ),
    ]
